version: '3.4'
services:
  recordsbackend: # name of the node backend
    image: recordsbackend:0.7
    ports:
      - "3000:3000" #specify ports mapping
    depends_on:
      - database # link this service to the database service
  
  database:
    image: mongo:4.4.3
    ports:
      - "27017:27017"
    volumes:
       - recordsdb_volume:/data/db
volumes:
  recordsdb_volume:
  

