apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  selector:
    app: database
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
spec:
  selector:
    matchLabels:
      app: database # has to match .spec.template.metadata.labels
  serviceName: "database"
  replicas: 1
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: mongo:4.2
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodata4
              mountPath: /data/db
      volumes:
        - name: mongodata4
          persistentVolumeClaim:
            claimName: mongo-pvc