apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: covers-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recordsbackend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recordsbackend
  template:
    metadata:
      labels:
        app: recordsbackend
    spec:
      containers:
        - name: recordsbackendcontainer
          image: recordsbackend:0.5
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
          volumeMounts:
            - name: coversvolume
              mountPath: /usr/src/recordsbackend/public
      volumes:
        - name: coversvolume
          persistentVolumeClaim:
            claimName: covers-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: recordsbackend
spec:
  selector:
    app: recordsbackend
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
  # type: LoadBalancer